-- Create Book table
CREATE TABLE BOOK (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  NO_OF_COPIES INT NOT NULL
);

-- Create User table
CREATE TABLE USER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  NO_OF_BOOKS_ALLOWED INT NOT NULL,
  EMAIL_ID VARCHAR(250) NOT NULL
);

ALTER TABLE BOOK ADD FOREIGN KEY (id) REFERENCES USER(id);

ALTER TABLE USER ADD FOREIGN KEY (id) REFERENCES BOOK(id);